import os
import argparse
import json
import csv
from datetime import datetime
import subprocess
import time
import torch
import torch.nn.functional as F
from torch.optim import AdamW
from torch_geometric.loader import DataLoader
from sklearn.metrics import precision_recall_fscore_support

from ema_pytorch import EMA

from RIdiffusion import HEGNN, RIdiffusion, seq_recovery
from dataset_src.large_dataset import RNAsolo


def list_graph_ids(base_dir: str, split: str):
    """
    Returns relative file paths (under base_dir) for .pt graphs in the given split.
    Example: base_dir='graph_dataset/dataset_0.8/', split='train_0.8' ->
    ['train_0.8/XYZ.pt', ...]
    """
    split_dir = os.path.join(base_dir, split)
    if not os.path.isdir(split_dir):
        raise FileNotFoundError(f"Graph split directory not found: {split_dir}. Run generate_graph_ss.py first.")
    files = [f for f in os.listdir(split_dir) if f.endswith('.pt')]
    return [os.path.join(split, f) for f in files]


def build_config():
    """Minimal working config aligned with HEGNN and RIdiffusion expectations."""
    return {
        'manifold': 'PoincareBall',
        'num_layers': 2,              # for HNN sanity check
        'c': 1.0,                     # curvature for hyperbolic ops
        'dropout': 0.0,

        # HNN-specific (required by hyp_utils.get_dim_act_curv / HNN)
        'act': 'relu',                # activation name in torch.nn.functional
        'dim': 128,                   # hidden dim for HNN layers
        'bias': True,                 # use bias in HypLinear / HNNLayer
        'task': 'rec',                # task type used to size curvatures
        'cuda': -1,                   # -1 for CPU; set 0 for GPU if desired
        'device': 'cuda',              # device string used when cuda != -1

        # HEGNN core
        'hidden_dim': 128,
        'depth': 4,
        'drop_out': 0.1,
        'update_edge': True,
        'embedding': True,            # use embedded dims consistently
        'embedding_dim': 128,         # must match hyp encoder output
        'embed_ss': -1,               # fuse ss after message passing
        'norm_feat': False,

        # Feature dims (used when embedding=False; kept for completeness)
        'input_feat_dim': 128,
        'edge_attr_dim': 128,

        # Diffusion
        'timesteps': 500,
        'noise_type': 'uniform',
        'loss_type': 'CE',
        'objective': 'pred_x0',
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--graph_root', type=str, default='graph_dataset/dataset_0.8',
                        help='Root folder of preprocessed graphs (generated by generate_graph_ss.py)')
    parser.add_argument('--train_split', type=str, default='train_0.8',
                        help='Subfolder under graph_root for training graphs')
    parser.add_argument('--val_split', type=str, default='validation_0.8',
                        help='Subfolder under graph_root for validation graphs')
    parser.add_argument('--test_split', type=str, default='test_0.8',
                        help='Subfolder under graph_root for test graphs')
    parser.add_argument('--batch_size', type=int, default=1, help='PyG DataLoader batch size')
    parser.add_argument('--epochs', type=int, default=20, help='Number of training epochs')
    parser.add_argument('--lr', type=float, default=3e-4, help='Learning rate')
    parser.add_argument('--weight_decay', type=float, default=1e-4, help='AdamW weight decay')
    parser.add_argument('--ema_decay', type=float, default=0.995, help='EMA decay rate')
    parser.add_argument('--save_dir', type=str, default='./weight', help='Directory to save checkpoints')
    parser.add_argument('--save_name', type=str, default='weight_custom.pt', help='Checkpoint filename')
    # Run management
    parser.add_argument('--runs_dir', type=str, default='./runs',
                        help='Directory to store per-run logs, configs, and checkpoints')
    parser.add_argument('--exp_name', type=str, default='classical_hegnn',
                        help='Experiment name used to create run subdirectory')
    parser.add_argument('--note', type=str, default='',
                        help='Optional note recorded in run metadata')
    parser.add_argument('--cuda_device', type=int, default=0, help='CUDA device index; set -1 for CPU')
    args = parser.parse_args()

    if torch.cuda.is_available() and args.cuda_device >= 0:
        chosen_idx = args.cuda_device
        if chosen_idx >= torch.cuda.device_count():
            chosen_idx = 0
        torch.cuda.set_device(chosen_idx)
        device = torch.device(f'cuda:{chosen_idx}')
    else:
        chosen_idx = -1
        device = torch.device('cpu')

    # Build datasets
    train_ids = list_graph_ids(args.graph_root, args.train_split)
    val_ids = list_graph_ids(args.graph_root, args.val_split)

    train_ds = RNAsolo(train_ids, baseDIR=args.graph_root + '/')
    val_ds = RNAsolo(val_ids, baseDIR=args.graph_root + '/')

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True)
    val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False)

    # Build config, model, diffusion
    config = build_config()
    gnn = HEGNN(config,
                input_feat_dim=config['input_feat_dim'],
                hidden_channels=config['hidden_dim'],
                edge_attr_dim=config['edge_attr_dim'],
                dropout=config['drop_out'],
                n_layers=config['depth'],
                update_edge=config['update_edge'],
                embedding=config['embedding'],
                embedding_dim=config['embedding_dim'],
                embed_ss=config['embed_ss'],
                norm_feat=config['norm_feat'])

    diffusion = RIdiffusion(model=gnn,
                            timesteps=config['timesteps'],
                            loss_type=config['loss_type'],
                            objective=config['objective'],
                            config=config).to(device)

    # Optimizer + EMA
    opt = AdamW(diffusion.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    ema = EMA(diffusion, beta=args.ema_decay)

    os.makedirs(args.save_dir, exist_ok=True)

    # ----- Run directory, logging, and metadata -----
    timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
    run_dir = os.path.join(args.runs_dir, f"{args.exp_name}_{timestamp}")
    os.makedirs(run_dir, exist_ok=True)
    log_path = os.path.join(run_dir, 'train.log')
    metrics_path = os.path.join(run_dir, 'metrics.csv')

    def log(msg: str):
        print(msg)
        try:
            with open(log_path, 'a', encoding='utf-8') as f:
                f.write(msg + "\n")
        except Exception:
            pass

    # metrics header
    try:
        with open(metrics_path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['epoch', 'train_loss', 'train_recovery', 'val_loss', 'val_recovery', 'is_best'])
    except Exception as e:
        log(f"[train] Warning: failed to init metrics.csv: {e}")

    def get_git_meta():
        meta = {}
        try:
            sha = subprocess.check_output(['git', 'rev-parse', 'HEAD']).decode().strip()
            meta['git_sha'] = sha
            try:
                branch = subprocess.check_output(['git', 'branch', '--show-current']).decode().strip()
                meta['git_branch'] = branch
            except Exception:
                pass
            tag = subprocess.run(['git', 'describe', '--tags', '--always'], capture_output=True)
            if tag.returncode == 0:
                meta['git_tag'] = tag.stdout.decode().strip()
            status = subprocess.check_output(['git', 'status', '--porcelain']).decode()
            meta['git_dirty'] = (len(status.strip()) > 0)
        except Exception as e:
            meta['git_error'] = str(e)
        return meta

    run_meta = {
        'timestamp': timestamp,
        'note': args.note,
        'device': str(device),
        'torch_version': torch.__version__,
        'cuda_available': torch.cuda.is_available(),
        'cuda_device_index': chosen_idx,
        'graph_root': args.graph_root,
        'splits': {'train': args.train_split, 'val': args.val_split},
        'git': get_git_meta(),
    }
    try:
        with open(os.path.join(run_dir, 'meta.json'), 'w', encoding='utf-8') as f:
            json.dump(run_meta, f, indent=2)
        with open(os.path.join(run_dir, 'config_model.json'), 'w', encoding='utf-8') as f:
            json.dump(config, f, indent=2)
        with open(os.path.join(run_dir, 'config_args.json'), 'w', encoding='utf-8') as f:
            json.dump(vars(args), f, indent=2)
        with open(os.path.join(run_dir, 'train_ids.json'), 'w', encoding='utf-8') as f:
            json.dump(train_ids, f, indent=2)
        with open(os.path.join(run_dir, 'val_ids.json'), 'w', encoding='utf-8') as f:
            json.dump(val_ids, f, indent=2)
    except Exception as e:
        log(f"[train] Warning: failed to write run configs: {e}")

    def train_one_epoch(epoch):
        diffusion.train()
        total_loss = 0.0
        total_correct = 0
        total_nodes = 0
        for batch in train_loader:
            # Each batch is a list of Data or a single Data depending on python
            # Ensure we move to device and handle Batch appropriately
            data = batch.to(device)
            opt.zero_grad(set_to_none=True)
            # 使用 logits 计算训练集 recovery，同时进行正常反向传播
            loss, pred_logits = diffusion.forward(data, logit=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(diffusion.parameters(), max_norm=1.0)
            opt.step()
            ema.update()
            total_loss += loss.item()
            # 统计训练集 recovery
            pred_seq = F.one_hot(pred_logits.argmax(dim=1), num_classes=4).float()
            recovery, ind = seq_recovery(data, pred_seq)
            total_correct += ind.sum().item()
            total_nodes += ind.shape[0]
        avg = total_loss / max(len(train_loader), 1)
        train_rec = total_correct / max(total_nodes, 1)
        log(f"Epoch {epoch} | train_loss: {avg:.4f} | train_recovery: {train_rec:.4f}")
        return avg, train_rec

    @torch.no_grad()
    def validate():
        diffusion.eval()
        total_loss = 0.0
        total_correct = 0
        total_nodes = 0
        for batch in val_loader:
            data = batch.to(device)
            # 获取预测 logits 以计算 recovery
            loss, pred_logits = diffusion.forward(data, logit=True)
            total_loss += loss.item()

            pred_seq = F.one_hot(pred_logits.argmax(dim=1), num_classes=4).float()
            recovery, ind = seq_recovery(data, pred_seq)
            total_correct += ind.sum().item()
            total_nodes += ind.shape[0]

        avg_loss = total_loss / max(len(val_loader), 1)
        avg_recovery = total_correct / max(total_nodes, 1)
        log(f"val_loss: {avg_loss:.4f} | val_recovery: {avg_recovery:.4f}")
        return avg_loss, avg_recovery

    @torch.no_grad()
    def evaluate_loader(model, loader):
        model.eval()
        total_loss = 0.0
        total_correct = 0
        total_nodes = 0
        for batch in loader:
            data = batch.to(device)
            loss, pred_logits = model.forward(data, logit=True)
            total_loss += loss.item()
            pred_seq = F.one_hot(pred_logits.argmax(dim=1), num_classes=4).float()
            recovery, ind = seq_recovery(data, pred_seq)
            total_correct += ind.sum().item()
            total_nodes += ind.shape[0]
        avg_loss = total_loss / max(len(loader), 1)
        avg_recovery = total_correct / max(total_nodes, 1)
        return avg_loss, avg_recovery

    @torch.no_grad()
    def evaluate_loader_detailed(model, loader):
        model.eval()
        total_loss = 0.0
        total_correct = 0
        total_nodes = 0
        per_seq_rec_list = []
        y_true_all = []
        y_pred_all = []
        for batch in loader:
            data = batch.to(device)
            loss, pred_logits = model.forward(data, logit=True)
            total_loss += loss.item()
            pred = pred_logits.argmax(dim=1)
            pred_seq = F.one_hot(pred, num_classes=4).float()
            _, ind = seq_recovery(data, pred_seq)
            total_correct += ind.sum().item()
            total_nodes += ind.shape[0]
            if hasattr(data, 'batch'):
                uniq = torch.unique(data.batch)
                for gid in uniq:
                    mask = (data.batch == gid)
                    if mask.any():
                        per_seq_rec_list.append(ind[mask].float().mean().item())
            y_true = data.x[:, :4].argmax(dim=1)
            y_true_all.append(y_true.cpu())
            y_pred_all.append(pred.cpu())
        rec_node = total_correct / max(total_nodes, 1)
        rec_seq = (sum(per_seq_rec_list) / len(per_seq_rec_list)) if len(per_seq_rec_list) > 0 else float('nan')
        f1_macro = float('nan')
        if len(y_true_all) > 0:
            yt = torch.cat(y_true_all).numpy()
            yp = torch.cat(y_pred_all).numpy()
            _, _, f1_macro, _ = precision_recall_fscore_support(yt, yp, labels=[0, 1, 2, 3], average='macro')
        avg_loss = total_loss / max(len(loader), 1)
        return avg_loss, rec_node, rec_seq, f1_macro

    # 以最高的 val_recovery 作为最佳模型标准
    best_recovery = float('-inf')
    for epoch in range(1, args.epochs + 1):
        _t0 = time.time()
        train_loss, train_recovery = train_one_epoch(epoch)
        _t1 = time.time()
        log(f"Epoch {epoch} | train_time: {_t1 - _t0:.2f}s")
        val_loss, val_recovery = validate()
        # Save best-by-recovery
        if val_recovery > best_recovery:
            best_recovery = val_recovery
            ckpt = {
                'ema': ema.state_dict(),
                'model': diffusion.state_dict(),
                'config': config,
                'val_loss': val_loss,
                'val_recovery': val_recovery,
                'epoch': epoch,
                'args': vars(args),
                'meta': run_meta,
            }
            save_path = os.path.join(args.save_dir, args.save_name)
            torch.save(ckpt, save_path)
            log(f"Saved checkpoint (best by recovery): {save_path}")
            # also save under run directory
            try:
                run_ckpt_path = os.path.join(run_dir, 'best.pt')
                torch.save(ckpt, run_ckpt_path)
                log(f"Saved run checkpoint: {run_ckpt_path}")
            except Exception as e:
                log(f"[train] Warning: failed to save run checkpoint: {e}")

        # append metrics row for this epoch
        try:
            with open(metrics_path, 'a', newline='') as f:
                writer = csv.writer(f)
                writer.writerow([epoch, f"{train_loss:.6f}", f"{train_recovery:.6f}", f"{val_loss:.6f}", f"{val_recovery:.6f}", int(val_recovery == best_recovery)])
        except Exception as e:
            log(f"[train] Warning: failed to log metrics: {e}")

    try:
        test_ids = list_graph_ids(args.graph_root, args.test_split)
        test_ds = RNAsolo(test_ids, baseDIR=args.graph_root + '/')
        test_loader = DataLoader(test_ds, batch_size=args.batch_size, shuffle=False)
        try:
            run_ckpt_path = os.path.join(run_dir, 'best.pt')
            ckpt = torch.load(run_ckpt_path, map_location=device)
        except Exception:
            save_path = os.path.join(args.save_dir, args.save_name)
            ckpt = torch.load(save_path, map_location=device)
        diffusion.load_state_dict(ckpt['model'])
        test_loss, recovery_node_level, recovery_seq_level, macro_f1 = evaluate_loader_detailed(diffusion, test_loader)
        log(f"test_loss: {test_loss:.4f} | recovery_node_level: {recovery_node_level:.4f} | recovery_seq_level: {recovery_seq_level:.4f} | macro_F1: {macro_f1:.4f}")
    except Exception as e:
        log(f"[train] Warning: test inference skipped: {e}")


if __name__ == '__main__':
    main()
