import os
import argparse
import json
import csv
from datetime import datetime
import subprocess
import torch
import torch.nn.functional as F
from torch.optim import AdamW
from torch_geometric.loader import DataLoader

from ema_pytorch import EMA

from RIdiffusion import HEGNN, RIdiffusion, seq_recovery
from dataset_src.large_dataset import RNAsolo
from qcbm3 import QCBM
import random
import numpy as np


def list_graph_ids(base_dir: str, split: str):
    """
    Returns relative file paths (under base_dir) for .pt graphs in the given split.
    Example: base_dir='graph_dataset/dataset_0.8/', split='train_0.8' ->
    ['train_0.8/XYZ.pt', ...]
    """
    split_dir = os.path.join(base_dir, split)
    if not os.path.isdir(split_dir):
        raise FileNotFoundError(f"Graph split directory not found: {split_dir}. Run generate_graph_ss.py first.")
    files = [f for f in os.listdir(split_dir) if f.endswith('.pt')]
    return [os.path.join(split, f) for f in files]


def build_config():
    """Minimal working config aligned with HEGNN and RIdiffusion expectations."""
    return {
        'manifold': 'PoincareBall',
        'num_layers': 2,              # for HNN sanity check
        'c': 1.0,                     # curvature for hyperbolic ops
        'dropout': 0.0,

        # HNN-specific (required by hyp_utils.get_dim_act_curv / HNN)
        'act': 'relu',                # activation name in torch.nn.functional
        'dim': 128,                   # hidden dim for HNN layers
        'bias': True,                 # use bias in HypLinear / HNNLayer
        'task': 'rec',                # task type used to size curvatures
        'cuda': -1,                   # -1 for CPU; set 0 for GPU if desired
        'device': 'cuda',              # device string used when cuda != -1

        # HEGNN core
        'hidden_dim': 128,
        'depth': 4,
        'drop_out': 0.1,
        'update_edge': True,
        'embedding': True,            # use embedded dims consistently
        'embedding_dim': 128,         # must match hyp encoder output
        'embed_ss': -1,               # fuse ss after message passing
        'norm_feat': False,

        # Feature dims (used when embedding=False; kept for completeness)
        'input_feat_dim': 128,
        'edge_attr_dim': 128,

        # Diffusion
        'timesteps': 500,
        'noise_type': 'uniform',
        'loss_type': 'CE',
        'objective': 'pred_x0',
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--graph_root', type=str, default='graph_dataset/dataset_0.8',
                        help='Root folder of preprocessed graphs (generated by generate_graph_ss.py)')
    parser.add_argument('--train_split', type=str, default='train_0.8',
                        help='Subfolder under graph_root for training graphs')
    parser.add_argument('--val_split', type=str, default='validation_0.8',
                        help='Subfolder under graph_root for validation graphs')
    parser.add_argument('--batch_size', type=int, default=1, help='PyG DataLoader batch size')
    parser.add_argument('--epochs', type=int, default=20, help='Number of training epochs')
    parser.add_argument('--lr', type=float, default=3e-4, help='Learning rate')
    parser.add_argument('--weight_decay', type=float, default=1e-4, help='AdamW weight decay')
    parser.add_argument('--ema_decay', type=float, default=0.995, help='EMA decay rate')
    parser.add_argument('--save_dir', type=str, default='./weight', help='Directory to save checkpoints')
    parser.add_argument('--save_name', type=str, default='weight_custom.pt', help='Checkpoint filename')
    # Run management
    parser.add_argument('--runs_dir', type=str, default='./runs',
                        help='Directory to store per-run logs, configs, and checkpoints')
    parser.add_argument('--exp_name', type=str, default='classical_hegnn',
                        help='Experiment name used to create run subdirectory')
    parser.add_argument('--note', type=str, default='',
                        help='Optional note recorded in run metadata')
    args = parser.parse_args()

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # Build datasets
    train_ids = list_graph_ids(args.graph_root, args.train_split)
    val_ids = list_graph_ids(args.graph_root, args.val_split)

    train_ds = RNAsolo(train_ids, baseDIR=args.graph_root + '/')
    val_ds = RNAsolo(val_ids, baseDIR=args.graph_root + '/')

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True)
    val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False)

    # Build config, model, diffusion
    config = build_config()
    gnn = HEGNN(config,
                input_feat_dim=config['input_feat_dim'],
                hidden_channels=config['hidden_dim'],
                edge_attr_dim=config['edge_attr_dim'],
                dropout=config['drop_out'],
                n_layers=config['depth'],
                update_edge=config['update_edge'],
                embedding=config['embedding'],
                embedding_dim=config['embedding_dim'],
                embed_ss=config['embed_ss'],
                norm_feat=config['norm_feat'])

    diffusion = RIdiffusion(model=gnn,
                            timesteps=config['timesteps'],
                            loss_type=config['loss_type'],
                            objective=config['objective'],
                            config={**config, 'num_qubits': 9, 'prior_weight': 0.5}).to(device)

    # Initialize QCBM
    qcbm = QCBM(num_qubits=9, num_layers=3)

    # Generate prior dataset: one prior sample per RNA sequence in train set
    def generate_prior_dataset(n_sequences):
        samples = qcbm.sample(num_samples=n_sequences)
        # convert to torch tensor [n_sequences, num_qubits]
        return torch.tensor(samples, dtype=torch.float32)

    prior_dataset = generate_prior_dataset(len(train_ids)).to(device)

    # Map batch graphs to prior samples via gid added in RNAsolo
    def fetch_prior_bits_for_batch(batch):
        # batch is PyG Batch; needs per-graph bitstrings -> per-node via batch.batch
        # Collect unique graph ids in batch order 0..G-1
        # We stored Data.gid during dataset get(index)
        # Build per-graph prior bits tensor [G, num_qubits]
        # Then diffusion will expand via data.batch
        # Determine G from last graph id in batch
        graph_ids = []
        # PyG Batch keeps slices; we can reconstruct per-graph ids from batch.gid sliced by nodes
        # Here, simply read gid of first node per graph using scatter_min
        gid_per_node = batch.gid
        # get unique gids in order of appearance
        # use torch.unique_consecutive to preserve order
        gids = torch.unique_consecutive(gid_per_node)
        graph_ids = gids.tolist()
        prior_bits_graph = prior_dataset[graph_ids]
        return prior_bits_graph

    # Optimizer + EMA
    opt = AdamW(diffusion.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    ema = EMA(diffusion, beta=args.ema_decay)

    os.makedirs(args.save_dir, exist_ok=True)

    # ----- Run directory, logging, and metadata -----
    timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
    run_dir = os.path.join(args.runs_dir, f"{args.exp_name}_{timestamp}")
    os.makedirs(run_dir, exist_ok=True)
    log_path = os.path.join(run_dir, 'train.log')
    metrics_path = os.path.join(run_dir, 'metrics.csv')

    def log(msg: str):
        print(msg)
        try:
            with open(log_path, 'a', encoding='utf-8') as f:
                f.write(msg + "\n")
        except Exception:
            pass

    # metrics header
    try:
        with open(metrics_path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['epoch', 'train_loss', 'train_recovery', 'val_loss', 'val_recovery', 'is_best'])
    except Exception as e:
        log(f"[train] Warning: failed to init metrics.csv: {e}")

    def get_git_meta():
        meta = {}
        try:
            sha = subprocess.check_output(['git', 'rev-parse', 'HEAD']).decode().strip()
            meta['git_sha'] = sha
            try:
                branch = subprocess.check_output(['git', 'branch', '--show-current']).decode().strip()
                meta['git_branch'] = branch
            except Exception:
                pass
            tag = subprocess.run(['git', 'describe', '--tags', '--always'], capture_output=True)
            if tag.returncode == 0:
                meta['git_tag'] = tag.stdout.decode().strip()
            status = subprocess.check_output(['git', 'status', '--porcelain']).decode()
            meta['git_dirty'] = (len(status.strip()) > 0)
        except Exception as e:
            meta['git_error'] = str(e)
        return meta

    run_meta = {
        'timestamp': timestamp,
        'note': args.note,
        'device': str(device),
        'torch_version': torch.__version__,
        'cuda_available': torch.cuda.is_available(),
        'graph_root': args.graph_root,
        'splits': {'train': args.train_split, 'val': args.val_split},
        'git': get_git_meta(),
    }
    try:
        with open(os.path.join(run_dir, 'meta.json'), 'w', encoding='utf-8') as f:
            json.dump(run_meta, f, indent=2)
        with open(os.path.join(run_dir, 'config_model.json'), 'w', encoding='utf-8') as f:
            json.dump(config, f, indent=2)
        with open(os.path.join(run_dir, 'config_args.json'), 'w', encoding='utf-8') as f:
            json.dump(vars(args), f, indent=2)
        with open(os.path.join(run_dir, 'train_ids.json'), 'w', encoding='utf-8') as f:
            json.dump(train_ids, f, indent=2)
        with open(os.path.join(run_dir, 'val_ids.json'), 'w', encoding='utf-8') as f:
            json.dump(val_ids, f, indent=2)
    except Exception as e:
        log(f"[train] Warning: failed to write run configs: {e}")

    def train_one_epoch(epoch):
        diffusion.train()
        total_loss = 0.0
        total_correct = 0
        total_nodes = 0
        for batch in train_loader:
            data = batch.to(device)
            opt.zero_grad(set_to_none=True)
            # Prepare prior bits per graph and fuse with weight
            prior_bits_graph = fetch_prior_bits_for_batch(data)
            loss, pred_logits = diffusion.forward(data, logit=True, prior_bits_per_graph=prior_bits_graph, w=0.5)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(diffusion.parameters(), max_norm=1.0)
            opt.step()
            ema.update()
            total_loss += loss.item()
            pred_seq = F.one_hot(pred_logits.argmax(dim=1), num_classes=4).float()
            recovery, ind = seq_recovery(data, pred_seq)
            total_correct += ind.sum().item()
            total_nodes += ind.shape[0]
        avg = total_loss / max(len(train_loader), 1)
        train_rec = total_correct / max(total_nodes, 1)
        log(f"Epoch {epoch} | train_loss: {avg:.4f} | train_recovery: {train_rec:.4f}")
        return avg, train_rec

    @torch.no_grad()
    def validate():
        diffusion.eval()
        total_loss = 0.0
        total_correct = 0
        total_nodes = 0
        # 1) 用训练好的QCBM采样20000个先验样本
        samples_20k = qcbm.sample(num_samples=20000)
        # 2) 统计每个唯一样本的采样次数，并按频率从高到低排序
        from collections import Counter
        tuples = [tuple(int(b) for b in s) for s in samples_20k]
        freq_counter = Counter(tuples)
        unique_states = list(freq_counter.items())  # [(state_tuple, count), ...]
        unique_states.sort(key=lambda x: x[1], reverse=True)

        # 3) 构造混合策略的验证先验数据集（大小等于验证集样本数），比例 Top 50% / Mid 30% / Tail 20%
        if len(unique_states) == 0:
            # 兜底：如果没有采样到任何状态（极端情况），随机生成
            num_qubits = prior_dataset.shape[1]
            val_prior_dataset = torch.randint(0, 2, (len(val_ids), num_qubits), dtype=torch.float32, device=device)
        else:
            U = len(unique_states)
            top_end = max(1, int(0.5 * U))
            mid_end = max(top_end + 1, int(0.8 * U))
            top_states = [state for state, _ in unique_states[:top_end]]
            mid_states = [state for state, _ in unique_states[top_end:mid_end]]
            tail_states = [state for state, _ in unique_states[mid_end:]]

            n_val = len(val_ids)
            n_top = int(0.5 * n_val)
            n_mid = int(0.3 * n_val)
            n_tail = n_val - n_top - n_mid

            def pick(states, n):
                if len(states) == 0:
                    return []
                return [random.choice(states) for _ in range(n)]

            mixed_list = pick(top_states, n_top) + pick(mid_states, n_mid) + pick(tail_states, n_tail)
            random.shuffle(mixed_list)
            val_prior_dataset = torch.tensor(mixed_list, dtype=torch.float32, device=device)

        # 4) 验证循环：按batch将混合策略的先验分配给对应的图
        for batch in val_loader:
            data = batch.to(device)
            gids = torch.unique_consecutive(data.gid)
            prior_bits_graph = val_prior_dataset[gids.tolist()]
            loss, pred_logits = diffusion.forward(data, logit=True, prior_bits_per_graph=prior_bits_graph, w=0.5)
            total_loss += loss.item()
            pred_seq = F.one_hot(pred_logits.argmax(dim=1), num_classes=4).float()
            recovery, ind = seq_recovery(data, pred_seq)
            total_correct += ind.sum().item()
            total_nodes += ind.shape[0]
        avg_loss = total_loss / max(len(val_loader), 1)
        avg_recovery = total_correct / max(total_nodes, 1)
        log(f"val_loss: {avg_loss:.4f} | val_recovery: {avg_recovery:.4f}")
        return avg_loss, avg_recovery

    @torch.no_grad()
    def compute_prior_scores():
        diffusion.eval()
        # Score each prior sample by passing through model over training set; average duplicates
        # We will compute a score per sequence: use sequence-level recovery proxy
        scores = torch.zeros(len(train_ids), device=device)
        counts = torch.zeros(len(train_ids), device=device)
        for batch in train_loader:
            data = batch.to(device)
            prior_bits_graph = fetch_prior_bits_for_batch(data)
            _, pred_logits = diffusion.forward(data, logit=True, prior_bits_per_graph=prior_bits_graph, w=0.5)
            pred_seq = F.one_hot(pred_logits.argmax(dim=1), num_classes=4).float()
            recovery, ind = seq_recovery(data, pred_seq)
            # assign recovery per graph: average node-wise correctness
            # compute per-graph mean of ind via scatter
            node_graph = data.batch
            per_graph_sum = torch.zeros(int(node_graph.max().item())+1, device=device)
            per_graph_cnt = torch.zeros_like(per_graph_sum)
            per_graph_sum.index_add_(0, node_graph, ind.float())
            per_graph_cnt.index_add_(0, node_graph, torch.ones_like(ind, dtype=torch.float, device=device))
            per_graph_rec = per_graph_sum / (per_graph_cnt + 1e-6)
            # Map graph ids to global sequence ids via gids
            gids = torch.unique_consecutive(data.gid)
            scores[gids] = per_graph_rec
            counts[gids] = counts[gids] + 1
        # Average duplicates
        counts = torch.clamp(counts, min=1.0)
        scores = scores / counts
        return scores

    def optimize_qcbm_with_target(scores):
        # Build target distribution via softmax over scores
        target = torch.softmax(scores, dim=0).detach().cpu().numpy()
        # Define KL divergence objective between target and qcbm predicted distribution via sampling counts
        from scipy.optimize import minimize
        def objective(params):
            qcbm.set_parameters(params)
            counts = qcbm.sample(num_samples=len(train_ids))
            # convert samples to strings and count unique according to sequence ids order
            # We use one-to-one mapping: sequence i uses sample i
            # So predicted prob mass is uniform over indices present; we approximate via repeated sampling frequency per unique sample
            # Build frequency of unique samples and align to unique of prior_dataset
            # For simplicity, use histogram over rows of prior_dataset
            import numpy as np
            arr = counts
            # map each sampled bitstring to index of its first occurrence in prior_dataset; fallback to uniform
            # create lookup: bitstring->indices list
            prior_np = prior_dataset.detach().cpu().numpy()
            lookup = {tuple(prior_np[i].tolist()): i for i in range(prior_np.shape[0])}
            freq = np.zeros(len(train_ids), dtype=np.float64)
            for s in arr:
                key = tuple([int(b) for b in s])
                idx = lookup.get(key, None)
                if idx is not None:
                    freq[idx] += 1
            if freq.sum() == 0:
                freq[:] = 1.0
            pred = freq / freq.sum()
            eps = 1e-8
            kl = np.sum(target * np.log((target + eps) / (pred + eps)))
            return kl
        init = qcbm.params
        res = minimize(objective, np.array(init, dtype=float), method='SLSQP', options={'maxiter': 50, 'disp': False})
        if res.success:
            qcbm.set_parameters(res.x)
        # Regenerate prior dataset
        new_prior = generate_prior_dataset(len(train_ids)).to(device)
        return new_prior

    # Training loop with QCBM integration
    best_recovery = float('-inf')
    for epoch in range(1, args.epochs + 1):
        train_loss, train_recovery = train_one_epoch(epoch)
        # After epoch: compute scores and update QCBM
        scores = compute_prior_scores()
        prior_dataset = optimize_qcbm_with_target(scores)
        # Validation
        val_loss, val_recovery = validate()
        # Save best-by-recovery
        if val_recovery > best_recovery:
            best_recovery = val_recovery
            ckpt = {
                'ema': ema.state_dict(),
                'model': diffusion.state_dict(),
                'config': config,
                'val_loss': val_loss,
                'val_recovery': val_recovery,
                'epoch': epoch,
                'args': vars(args),
                'meta': run_meta,
            }
            save_path = os.path.join(args.save_dir, args.save_name)
            torch.save(ckpt, save_path)
            log(f"Saved checkpoint (best by recovery): {save_path}")
            # also save under run directory
            try:
                run_ckpt_path = os.path.join(run_dir, 'best.pt')
                torch.save(ckpt, run_ckpt_path)
                log(f"Saved run checkpoint: {run_ckpt_path}")
            except Exception as e:
                log(f"[train] Warning: failed to save run checkpoint: {e}")

        # append metrics row for this epoch
        try:
            with open(metrics_path, 'a', newline='') as f:
                writer = csv.writer(f)
                writer.writerow([epoch, f"{train_loss:.6f}", f"{train_recovery:.6f}", f"{val_loss:.6f}", f"{val_recovery:.6f}", int(val_recovery == best_recovery)])
        except Exception as e:
            log(f"[train] Warning: failed to log metrics: {e}")


if __name__ == '__main__':
    main()
