import os
import argparse
import json
import csv
from datetime import datetime
import subprocess
import torch
import torch.nn.functional as F
from torch.optim import AdamW
from torch_geometric.loader import DataLoader
from sklearn.metrics import precision_recall_fscore_support

from ema_pytorch import EMA

from RIdiffusion import HEGNN, RIdiffusion, seq_recovery
from dataset_src.large_dataset import RNAsolo
from qcbm3 import QCBM
import random
import numpy as np


def list_graph_ids(base_dir: str, split: str):
    """
    Returns relative file paths (under base_dir) for .pt graphs in the given split.
    Example: base_dir='graph_dataset/dataset_0.8/', split='train_0.8' ->
    ['train_0.8/XYZ.pt', ...]
    """
    split_dir = os.path.join(base_dir, split)
    if not os.path.isdir(split_dir):
        raise FileNotFoundError(f"Graph split directory not found: {split_dir}. Run generate_graph_ss.py first.")
    files = [f for f in os.listdir(split_dir) if f.endswith('.pt')]
    return [os.path.join(split, f) for f in files]


def build_config():
    """Minimal working config aligned with HEGNN and RIdiffusion expectations."""
    return {
        'manifold': 'PoincareBall',
        'num_layers': 2,              # for HNN sanity check
        'c': 1.0,                     # curvature for hyperbolic ops
        'dropout': 0.0,

        # HNN-specific (required by hyp_utils.get_dim_act_curv / HNN)
        'act': 'relu',                # activation name in torch.nn.functional
        'dim': 128,                   # hidden dim for HNN layers
        'bias': True,                 # use bias in HypLinear / HNNLayer
        'task': 'rec',                # task type used to size curvatures
        'cuda': -1,                   # -1 for CPU; set 0 for GPU if desired
        'device': 'cuda',              # device string used when cuda != -1

        # HEGNN core
        'hidden_dim': 128,
        'depth': 4,
        'drop_out': 0.1,
        'update_edge': True,
        'embedding': True,            # use embedded dims consistently
        'embedding_dim': 128,         # must match hyp encoder output
        'embed_ss': -1,               # fuse ss after message passing
        'norm_feat': False,

        # Feature dims (used when embedding=False; kept for completeness)
        'input_feat_dim': 128,
        'edge_attr_dim': 128,

        # Diffusion
        'timesteps': 500,
        'noise_type': 'uniform',
        'loss_type': 'CE',
        'objective': 'pred_x0',
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--graph_root', type=str, default='graph_dataset/dataset_0.8',
                        help='Root folder of preprocessed graphs (generated by generate_graph_ss.py)')
    parser.add_argument('--prior_weight', type=float, default=0.5, help='Fusion weight for QCBM prior bias')
    parser.add_argument('--prior_n_qubits', type=int, default=9, help='Number of qubits for QCBM prior')
    parser.add_argument('--prior_n_layers', type=int, default=3, help='Number of layers for QCBM prior')
    parser.add_argument('--train_split', type=str, default='train_0.8',
                        help='Subfolder under graph_root for training graphs')
    parser.add_argument('--val_split', type=str, default='validation_0.8',
                        help='Subfolder under graph_root for validation graphs')
    parser.add_argument('--test_split', type=str, default='test_0.8',
                        help='Subfolder under graph_root for test graphs')
    parser.add_argument('--batch_size', type=int, default=1, help='PyG DataLoader batch size')
    parser.add_argument('--epochs', type=int, default=20, help='Number of training epochs')
    parser.add_argument('--lr', type=float, default=3e-4, help='Learning rate')
    parser.add_argument('--weight_decay', type=float, default=1e-4, help='AdamW weight decay')
    parser.add_argument('--ema_decay', type=float, default=0.995, help='EMA decay rate')
    parser.add_argument('--save_dir', type=str, default='./weight', help='Directory to save checkpoints')
    parser.add_argument('--save_name', type=str, default='weight_custom.pt', help='Checkpoint filename')
    # Run management
    parser.add_argument('--runs_dir', type=str, default='./runs',
                        help='Directory to store per-run logs, configs, and checkpoints')
    parser.add_argument('--exp_name', type=str, default='classical_hegnn',
                        help='Experiment name used to create run subdirectory')
    parser.add_argument('--note', type=str, default='',
                        help='Optional note recorded in run metadata')
    parser.add_argument('--cuda_device', type=int, default=0, help='CUDA device index; set -1 for CPU')
    args = parser.parse_args()

    device = torch.device(f'cuda:{args.cuda_device}') if (args.cuda_device >= 0 and torch.cuda.is_available()) else torch.device('cpu')

    # Build datasets
    train_ids = list_graph_ids(args.graph_root, args.train_split)
    val_ids = list_graph_ids(args.graph_root, args.val_split)

    train_ds = RNAsolo(train_ids, baseDIR=args.graph_root + '/')
    val_ds = RNAsolo(val_ids, baseDIR=args.graph_root + '/')

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True)
    val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False)

    # Build config, model, diffusion
    config = build_config()
    gnn = HEGNN(config,
                input_feat_dim=config['input_feat_dim'],
                hidden_channels=config['hidden_dim'],
                edge_attr_dim=config['edge_attr_dim'],
                dropout=config['drop_out'],
                n_layers=config['depth'],
                update_edge=config['update_edge'],
                embedding=config['embedding'],
                embedding_dim=config['embedding_dim'],
                embed_ss=config['embed_ss'],
                norm_feat=config['norm_feat'])

    diffusion = RIdiffusion(model=gnn,
                            timesteps=config['timesteps'],
                            loss_type=config['loss_type'],
                            objective=config['objective'],
                            config={**config, 'num_qubits': args.prior_n_qubits, 'prior_weight': args.prior_weight}).to(device)

    # Initialize QCBM
    qcbm = QCBM(num_qubits=args.prior_n_qubits, num_layers=args.prior_n_layers)

    # Generate prior dataset: one prior sample per RNA sequence in train set
    def generate_prior_dataset(n_sequences):
        samples = qcbm.sample(num_samples=n_sequences)
        # convert to torch tensor [n_sequences, num_qubits]
        return torch.tensor(samples, dtype=torch.float32)

    prior_dataset = generate_prior_dataset(len(train_ids)).to(device)

    # Map batch graphs to prior samples via gid added in RNAsolo
    def fetch_prior_bits_for_batch(batch):
        # batch is PyG Batch; needs per-graph bitstrings -> per-node via batch.batch
        # Collect unique graph ids in batch order 0..G-1
        # We stored Data.gid during dataset get(index)
        # Build per-graph prior bits tensor [G, num_qubits]
        # Then diffusion will expand via data.batch
        # Determine G from last graph id in batch
        graph_ids = []
        # PyG Batch keeps slices; we can reconstruct per-graph ids from batch.gid sliced by nodes
        # Here, simply read gid of first node per graph using scatter_min
        gid_per_node = batch.gid
        # get unique gids in order of appearance
        # use torch.unique_consecutive to preserve order
        gids = torch.unique_consecutive(gid_per_node)
        graph_ids = gids.tolist()
        prior_bits_graph = prior_dataset[graph_ids]
        return prior_bits_graph

    # Optimizer + EMA
    opt = AdamW(diffusion.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    ema = EMA(diffusion, beta=args.ema_decay)

    os.makedirs(args.save_dir, exist_ok=True)

    # ----- Run directory, logging, and metadata -----
    timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
    run_dir = os.path.join(args.runs_dir, f"{args.exp_name}_{timestamp}")
    os.makedirs(run_dir, exist_ok=True)
    log_path = os.path.join(run_dir, 'train.log')
    metrics_path = os.path.join(run_dir, 'metrics.csv')

    def log(msg: str):
        print(msg)
        try:
            with open(log_path, 'a', encoding='utf-8') as f:
                f.write(msg + "\n")
        except Exception:
            pass

    # metrics header
    try:
        with open(metrics_path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow([
                'epoch', 'train_loss', 'train_recovery', 'val_loss_baseline',
                'val_recovery_baseline', 'val_recovery_top', 'val_recovery_mid', 'val_recovery_tail', 'val_recovery_mixed',
                'is_best'
            ])
    except Exception as e:
        log(f"[train] Warning: failed to init metrics.csv: {e}")

    def get_git_meta():
        meta = {}
        try:
            sha = subprocess.check_output(['git', 'rev-parse', 'HEAD']).decode().strip()
            meta['git_sha'] = sha
            try:
                branch = subprocess.check_output(['git', 'branch', '--show-current']).decode().strip()
                meta['git_branch'] = branch
            except Exception:
                pass
            tag = subprocess.run(['git', 'describe', '--tags', '--always'], capture_output=True)
            if tag.returncode == 0:
                meta['git_tag'] = tag.stdout.decode().strip()
            status = subprocess.check_output(['git', 'status', '--porcelain']).decode()
            meta['git_dirty'] = (len(status.strip()) > 0)
        except Exception as e:
            meta['git_error'] = str(e)
        return meta

    run_meta = {
        'timestamp': timestamp,
        'note': args.note,
        'device': str(device),
        'torch_version': torch.__version__,
        'cuda_available': torch.cuda.is_available(),
        'graph_root': args.graph_root,
        'splits': {'train': args.train_split, 'val': args.val_split},
        'git': get_git_meta(),
    }
    try:
        with open(os.path.join(run_dir, 'meta.json'), 'w', encoding='utf-8') as f:
            json.dump(run_meta, f, indent=2)
        with open(os.path.join(run_dir, 'config_model.json'), 'w', encoding='utf-8') as f:
            json.dump(config, f, indent=2)
        with open(os.path.join(run_dir, 'config_args.json'), 'w', encoding='utf-8') as f:
            json.dump(vars(args), f, indent=2)
        with open(os.path.join(run_dir, 'train_ids.json'), 'w', encoding='utf-8') as f:
            json.dump(train_ids, f, indent=2)
        with open(os.path.join(run_dir, 'val_ids.json'), 'w', encoding='utf-8') as f:
            json.dump(val_ids, f, indent=2)
    except Exception as e:
        log(f"[train] Warning: failed to write run configs: {e}")

    # 收集跨epoch的验证汇总（不同先验策略的恢复率）
    aggregated_overall_rows = []
    overall_agg_path = os.path.join(run_dir, 'valid_overall_recovery_all_epochs.csv')

    def train_one_epoch(epoch):
        diffusion.train()
        total_loss = 0.0
        total_correct = 0
        total_nodes = 0
        for batch in train_loader:
            data = batch.to(device)
            opt.zero_grad(set_to_none=True)
            # Prepare prior bits per graph and fuse with weight
            prior_bits_graph = fetch_prior_bits_for_batch(data)
            loss, pred_logits = diffusion.forward(data, logit=True, prior_bits_per_graph=prior_bits_graph, w=args.prior_weight)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(diffusion.parameters(), max_norm=1.0)
            opt.step()
            ema.update()
            total_loss += loss.item()
            pred_seq = F.one_hot(pred_logits.argmax(dim=1), num_classes=4).float()
            recovery, ind = seq_recovery(data, pred_seq)
            total_correct += ind.sum().item()
            total_nodes += ind.shape[0]
        avg = total_loss / max(len(train_loader), 1)
        train_rec = total_correct / max(total_nodes, 1)
        log(f"Epoch {epoch} | train_loss: {avg:.4f} | train_recovery: {train_rec:.4f}")
        return avg, train_rec

    @torch.no_grad()
    def validate():
        diffusion.eval()
        # 基线：使用QCBM为验证集大小生成先验样本
        valid_dataset_size = max(1, len(val_ids))
        prior_baseline = torch.tensor(qcbm.sample(num_samples=valid_dataset_size), dtype=torch.float32, device=device)
        # 额外采样用于分层统计（唯一样本频次）
        validation_prior_samples = torch.tensor(qcbm.sample(num_samples=2048), dtype=torch.float32, device=device)
        perm = torch.randperm(validation_prior_samples.shape[0], device=device)
        validation_prior_samples = validation_prior_samples[perm]
        # 统计唯一比特串出现次数，并划分 Top 20% / Mid 60% / Tail 20%
        val_bits_np = (validation_prior_samples.detach().cpu().numpy()).astype(np.int64)
        uniques, counts = np.unique(val_bits_np, axis=0, return_counts=True)
        order = np.argsort(counts)[::-1]
        u = order.shape[0]
        top_end = int(0.2 * u)
        mid_end = top_end + int(0.6 * u)
        top_bits = uniques[order[:top_end]]
        mid_bits = uniques[order[top_end:mid_end]]
        tail_bits = uniques[order[mid_end:]]
        prior_top_set = torch.tensor(top_bits, dtype=torch.float32, device=device) if top_bits.size > 0 else torch.empty((0, validation_prior_samples.shape[1]), dtype=torch.float32, device=device)
        prior_mid_set = torch.tensor(mid_bits, dtype=torch.float32, device=device) if mid_bits.size > 0 else torch.empty((0, validation_prior_samples.shape[1]), dtype=torch.float32, device=device)
        prior_tail_set = torch.tensor(tail_bits, dtype=torch.float32, device=device) if tail_bits.size > 0 else torch.empty((0, validation_prior_samples.shape[1]), dtype=torch.float32, device=device)

        # 构造按比例混合的策略（Top50/Mid30/Tail20），有放回采样
        mixed_size = valid_dataset_size
        r_top, r_mid = 0.5, 0.3
        n_top = int(r_top * mixed_size)
        n_mid = int(r_mid * mixed_size)
        n_tail = mixed_size - n_top - n_mid
        mixed_parts = []
        if prior_top_set.shape[0] > 0 and n_top > 0:
            idx_top = torch.randint(low=0, high=prior_top_set.shape[0], size=(n_top,), device=device)
            mixed_parts.append(prior_top_set[idx_top])
        if prior_mid_set.shape[0] > 0 and n_mid > 0:
            idx_mid = torch.randint(low=0, high=prior_mid_set.shape[0], size=(n_mid,), device=device)
            mixed_parts.append(prior_mid_set[idx_mid])
        if prior_tail_set.shape[0] > 0 and n_tail > 0:
            idx_tail = torch.randint(low=0, high=prior_tail_set.shape[0], size=(n_tail,), device=device)
            mixed_parts.append(prior_tail_set[idx_tail])
        prior_mixed = torch.cat(mixed_parts, dim=0) if len(mixed_parts) > 0 else torch.empty((0, validation_prior_samples.shape[1]), dtype=torch.float32, device=device)

        # 为各策略生成与验证集大小匹配的先验数据集（Top/Mid/Tail 用各自集合有放回采样）
        def sample_prior_from_set(prior_set, size):
            if prior_set.shape[0] == 0 or size == 0:
                return torch.empty((0, validation_prior_samples.shape[1]), dtype=torch.float32, device=device)
            idx = torch.randint(low=0, high=prior_set.shape[0], size=(size,), device=device)
            return prior_set[idx]
        prior_top = sample_prior_from_set(prior_top_set, valid_dataset_size)
        prior_mid = sample_prior_from_set(prior_mid_set, valid_dataset_size)
        prior_tail = sample_prior_from_set(prior_tail_set, valid_dataset_size)

        # 统一的恢复率评估函数：按batch将先验比特分配到对应graph（通过gid）
        def eval_recovery_for_prior(prior_dataset_for_eval):
            total_loss = 0.0
            total_correct = 0
            total_nodes = 0
            per_seq_rec_list = []
            for batch in val_loader:
                data = batch.to(device)
                gids = torch.unique_consecutive(data.gid)
                if prior_dataset_for_eval.shape[0] == 0:
                    # 若为空策略，跳过该batch
                    continue
                prior_bits_graph = prior_dataset_for_eval[gids.tolist()]
                loss, pred_logits = diffusion.forward(data, logit=True, prior_bits_per_graph=prior_bits_graph, w=args.prior_weight)
                total_loss += loss.item()
                pred_seq = F.one_hot(pred_logits.argmax(dim=1), num_classes=4).float()
                _, ind = seq_recovery(data, pred_seq)
                total_correct += ind.sum().item()
                total_nodes += ind.shape[0]
                # 序列级恢复率：先按每个图统计节点正确率均值，再对所有图取平均
                if hasattr(data, 'batch'):
                    uniq = torch.unique(data.batch)
                    for gid in uniq:
                        mask = (data.batch == gid)
                        if mask.any():
                            per_seq_rec_list.append(ind[mask].float().mean().item())
            avg_loss = total_loss / max(len(val_loader), 1)
            avg_rec_node = total_correct / max(total_nodes, 1)
            avg_rec_seq = float(np.mean(per_seq_rec_list)) if len(per_seq_rec_list) > 0 else 0.0
            return avg_loss, avg_rec_node, avg_rec_seq
        # 在验证集上评估各策略
        base_loss, base_rec_node, base_rec_seq = eval_recovery_for_prior(prior_baseline)
        _, top_rec_node, top_rec_seq = eval_recovery_for_prior(prior_top)
        _, mid_rec_node, mid_rec_seq = eval_recovery_for_prior(prior_mid)
        _, tail_rec_node, tail_rec_seq = eval_recovery_for_prior(prior_tail)
        _, mixed_rec_node, mixed_rec_seq = eval_recovery_for_prior(prior_mixed)
        log(f"Validation (Baseline) Recovery - Node: {base_rec_node:.4f} | Seq: {base_rec_seq:.4f}")
        log(f"Validation Prior Group Recovery (Node) -> Top50%: {top_rec_node:.4f}, Mid30%: {mid_rec_node:.4f}, Tail20%: {tail_rec_node:.4f}, Mixed_T50_M30_T20: {mixed_rec_node:.4f}")
        log(f"Validation Prior Group Recovery (Seq)  -> Top50%: {top_rec_seq:.4f}, Mid30%: {mid_rec_seq:.4f}, Tail20%: {tail_rec_seq:.4f}, Mixed_T50_M30_T20: {mixed_rec_seq:.4f}")
        return base_loss, base_rec_node, base_rec_seq, top_rec_node, top_rec_seq, mid_rec_node, mid_rec_seq, tail_rec_node, tail_rec_seq, mixed_rec_node, mixed_rec_seq

    @torch.no_grad()
    def evaluate_loader_detailed(model, loader):
        model.eval()
        total_loss = 0.0
        total_correct = 0
        total_nodes = 0
        per_seq_rec_list = []
        y_true_all = []
        y_pred_all = []
        for batch in loader:
            data = batch.to(device)
            loss, pred_logits = model.forward(data, logit=True)
            total_loss += loss.item()
            pred = pred_logits.argmax(dim=1)
            pred_seq = F.one_hot(pred, num_classes=4).float()
            _, ind = seq_recovery(data, pred_seq)
            total_correct += ind.sum().item()
            total_nodes += ind.shape[0]
            if hasattr(data, 'batch'):
                uniq = torch.unique(data.batch)
                for gid in uniq:
                    mask = (data.batch == gid)
                    if mask.any():
                        per_seq_rec_list.append(ind[mask].float().mean().item())
            y_true = data.x[:, :4].argmax(dim=1)
            y_true_all.append(y_true.cpu())
            y_pred_all.append(pred.cpu())
        rec_node = total_correct / max(total_nodes, 1)
        rec_seq = (sum(per_seq_rec_list) / len(per_seq_rec_list)) if len(per_seq_rec_list) > 0 else float('nan')
        f1_macro = float('nan')
        if len(y_true_all) > 0:
            yt = torch.cat(y_true_all).numpy()
            yp = torch.cat(y_pred_all).numpy()
            try:
                _, _, f1_macro, _ = precision_recall_fscore_support(yt, yp, labels=[0, 1, 2, 3], average='macro')
            except Exception:
                pass
        avg_loss = total_loss / max(len(loader), 1)
        return avg_loss, rec_node, rec_seq, f1_macro

    @torch.no_grad()
    def compute_prior_scores():
        diffusion.eval()
        # 先收集每个图的分数到 all_scores，并记录对应的先验样本比特串 all_samples
        all_scores = []  # list of float
        all_samples = []  # list of tuple(bitstring)
        for batch in train_loader:
            data = batch.to(device)
            prior_bits_graph = fetch_prior_bits_for_batch(data)  # [G, num_qubits]
            _, pred_logits = diffusion.forward(data, logit=True, prior_bits_per_graph=prior_bits_graph, w=args.prior_weight)
            pred_seq = F.one_hot(pred_logits.argmax(dim=1), num_classes=4).float()
            recovery, ind = seq_recovery(data, pred_seq)
            # 计算每个图的节点正确率均值
            node_graph = data.batch
            per_graph_sum = torch.zeros(int(node_graph.max().item()) + 1, device=device)
            per_graph_cnt = torch.zeros_like(per_graph_sum)
            per_graph_sum.index_add_(0, node_graph, ind.float())
            per_graph_cnt.index_add_(0, node_graph, torch.ones_like(ind, dtype=torch.float, device=device))
            per_graph_rec = per_graph_sum / (per_graph_cnt + 1e-6)  # [G]
            # 依次记录每个图的分数以及其对应的先验样本（按比特串作为键）
            for i in range(prior_bits_graph.shape[0]):
                all_scores.append(float(per_graph_rec[i].item()))
                sample_key = tuple(int(x) for x in prior_bits_graph[i].detach().cpu().numpy().tolist())
                all_samples.append(sample_key)
        # 对重复采样的先验样本取平均分数
        unique_samples = {}
        for i, sample_key in enumerate(all_samples):
            if sample_key not in unique_samples:
                unique_samples[sample_key] = []
            unique_samples[sample_key].append(all_scores[i])
        # 按二进制字典序对唯一样本排序
        unique_sample_keys = list(unique_samples.keys())
        unique_sample_keys.sort(key=lambda x: int(''.join([str(int(bit)) for bit in x]), 2))
        # 计算每个唯一样本的平均分数
        unique_scores_list = []
        for sample_key in unique_sample_keys:
            scores_list = unique_samples[sample_key]
            avg_score = torch.tensor(scores_list, device=device, dtype=torch.float32).mean()
            unique_scores_list.append(avg_score)
        unique_scores = torch.stack(unique_scores_list)
        return unique_scores, unique_sample_keys

    def optimize_qcbm_with_target(unique_scores, unique_sample_keys):
        # 基于唯一样本的平均分数构造目标分布
        target = (unique_scores / (unique_scores.sum() + 1e-12)).detach().cpu().numpy()
        U = len(unique_sample_keys)
        key_to_idx = {tuple(k): i for i, k in enumerate(unique_sample_keys)}
        from scipy.optimize import minimize
        iter_state = {'i': 1, 'last_kl': None}
        def objective(params):
            qcbm.set_parameters(params)
            counts = qcbm.get_sample_counts(num_samples=len(train_ids))
            # 遍历唯一样本集合（U）来构造频率数组
            freq = np.zeros(U, dtype=np.float64)
            for i, sample_key in enumerate(unique_sample_keys):
                sample_str = ''.join([str(int(bit)) for bit in sample_key])
                freq[i] = counts.get(sample_str, 0)
            if freq.sum() == 0:
                freq[:] = 1.0
            pred = freq / freq.sum()
            eps = 1e-8
            kl = np.sum(target * np.log((target + eps) / (pred + eps)))
            iter_state['last_kl'] = kl
            return kl
        def callback(xk):
            kl_val = iter_state['last_kl']
            if kl_val is None:
                kl_val = objective(xk)
            log(f"[QCBM Optimize] iter={iter_state['i']} KL={kl_val:.6f}")
            iter_state['i'] += 1
            iter_state['last_kl'] = None
        init = qcbm.params
        res = minimize(objective, np.array(init, dtype=float), method='COBYLA', callback=callback, options={'maxiter': 0, 'disp': False})
        try:
            final_kl = objective(res.x if hasattr(res, 'x') else np.array(init, dtype=float))
            log(f"[QCBM Optimize] final KL after optimization: {final_kl:.6f}")
        except Exception as e_final:
            log(f"[QCBM Optimize] Warning: failed to compute final KL: {e_final}")
        if res.success:
            qcbm.set_parameters(res.x)
        # 更新后重新生成 prior 数据集（仍然按训练集样本数生成图级先验）
        new_prior = generate_prior_dataset(len(train_ids)).to(device)
        return new_prior

    # Training loop with QCBM integration
    best_recovery_seq = float('-inf')
    best_top_rec_seq = float('-inf')
    best_mid_rec_seq = float('-inf')
    best_tail_rec_seq = float('-inf')
    best_mixed_rec_seq = float('-inf')
    for epoch in range(1, args.epochs + 1):
        train_loss, train_recovery = train_one_epoch(epoch)
        # After epoch: compute scores and update QCBM
        unique_scores, unique_keys = compute_prior_scores()
        prior_dataset = optimize_qcbm_with_target(unique_scores, unique_keys)
        # Validation (multi-strategy)
        val_loss, base_rec_node, base_rec_seq, top_rec_node, top_rec_seq, mid_rec_node, mid_rec_seq, tail_rec_node, tail_rec_seq, mixed_rec_node, mixed_rec_seq = validate()
        # Save best-by-recovery (use baseline sequence recovery)
        if base_rec_seq > best_recovery_seq:
            best_recovery_seq = base_rec_seq
            ckpt = {
                'ema': ema.state_dict(),
                'model': diffusion.state_dict(),
                'config': config,
                'val_loss': val_loss,
                'val_recovery': base_rec_seq,
                'epoch': epoch,
                'args': vars(args),
                'meta': run_meta,
            }
            save_path = os.path.join(args.save_dir, args.save_name)
            torch.save(ckpt, save_path)
            log(f"Saved checkpoint (best by baseline sequence recovery): {save_path}")
            # also save under run directory
            try:
                run_ckpt_path = os.path.join(run_dir, 'best.pt')
                torch.save(ckpt, run_ckpt_path)
                log(f"Saved run checkpoint: {run_ckpt_path}")
                # uniform naming for baseline as well
                run_ckpt_base_path = os.path.join(run_dir, 'best_base.pt')
                torch.save(ckpt, run_ckpt_base_path)
                base_name, ext = os.path.splitext(args.save_name)
                variant_save_base = os.path.join(args.save_dir, f"{base_name}_base{ext}")
                torch.save(ckpt, variant_save_base)
                log(f"Saved baseline variant checkpoint: {variant_save_base}")
            except Exception as e:
                log(f"[train] Warning: failed to save run checkpoint: {e}")
        # Save best-by Top/Mid/Tail/Mixed recoveries (sequence-level)
        if top_rec_seq > best_top_rec_seq:
            best_top_rec_seq = top_rec_seq
            ckpt_top = {
                'ema': ema.state_dict(),
                'model': diffusion.state_dict(),
                'config': config,
                'val_loss': val_loss,
                'val_recovery': top_rec_seq,
                'epoch': epoch,
                'args': vars(args),
                'meta': run_meta,
            }
            try:
                run_ckpt_top_path = os.path.join(run_dir, 'best_top.pt')
                torch.save(ckpt_top, run_ckpt_top_path)
                base_name, ext = os.path.splitext(args.save_name)
                variant_save_top = os.path.join(args.save_dir, f"{base_name}_top{ext}")
                torch.save(ckpt_top, variant_save_top)
                log(f"Saved checkpoint (best by top sequence recovery): {run_ckpt_top_path} | {variant_save_top}")
            except Exception as e:
                log(f"[train] Warning: failed to save top checkpoint: {e}")
        if mid_rec_seq > best_mid_rec_seq:
            best_mid_rec_seq = mid_rec_seq
            ckpt_mid = {
                'ema': ema.state_dict(),
                'model': diffusion.state_dict(),
                'config': config,
                'val_loss': val_loss,
                'val_recovery': mid_rec_seq,
                'epoch': epoch,
                'args': vars(args),
                'meta': run_meta,
            }
            try:
                run_ckpt_mid_path = os.path.join(run_dir, 'best_mid.pt')
                torch.save(ckpt_mid, run_ckpt_mid_path)
                base_name, ext = os.path.splitext(args.save_name)
                variant_save_mid = os.path.join(args.save_dir, f"{base_name}_mid{ext}")
                torch.save(ckpt_mid, variant_save_mid)
                log(f"Saved checkpoint (best by mid sequence recovery): {run_ckpt_mid_path} | {variant_save_mid}")
            except Exception as e:
                log(f"[train] Warning: failed to save mid checkpoint: {e}")
        if tail_rec_seq > best_tail_rec_seq:
            best_tail_rec_seq = tail_rec_seq
            ckpt_tail = {
                'ema': ema.state_dict(),
                'model': diffusion.state_dict(),
                'config': config,
                'val_loss': val_loss,
                'val_recovery': tail_rec_seq,
                'epoch': epoch,
                'args': vars(args),
                'meta': run_meta,
            }
            try:
                run_ckpt_tail_path = os.path.join(run_dir, 'best_tail.pt')
                torch.save(ckpt_tail, run_ckpt_tail_path)
                base_name, ext = os.path.splitext(args.save_name)
                variant_save_tail = os.path.join(args.save_dir, f"{base_name}_tail{ext}")
                torch.save(ckpt_tail, variant_save_tail)
                log(f"Saved checkpoint (best by tail sequence recovery): {run_ckpt_tail_path} | {variant_save_tail}")
            except Exception as e:
                log(f"[train] Warning: failed to save tail checkpoint: {e}")
        if mixed_rec_seq > best_mixed_rec_seq:
            best_mixed_rec_seq = mixed_rec_seq
            ckpt_mixed = {
                'ema': ema.state_dict(),
                'model': diffusion.state_dict(),
                'config': config,
                'val_loss': val_loss,
                'val_recovery': mixed_rec_seq,
                'epoch': epoch,
                'args': vars(args),
                'meta': run_meta,
            }
            try:
                run_ckpt_mixed_path = os.path.join(run_dir, 'best_mixed.pt')
                torch.save(ckpt_mixed, run_ckpt_mixed_path)
                base_name, ext = os.path.splitext(args.save_name)
                variant_save_mixed = os.path.join(args.save_dir, f"{base_name}_mixed{ext}")
                torch.save(ckpt_mixed, variant_save_mixed)
                log(f"Saved checkpoint (best by mixed sequence recovery): {run_ckpt_mixed_path} | {variant_save_mixed}")
            except Exception as e:
                log(f"[train] Warning: failed to save mixed checkpoint: {e}")

        # append metrics row for this epoch
        try:
            with open(metrics_path, 'a', newline='') as f:
                writer = csv.writer(f)
                writer.writerow([
                    epoch,
                    f"{train_loss:.6f}", f"{train_recovery:.6f}", f"{val_loss:.6f}",
                    f"{base_rec_node:.6f}", f"{top_rec_node:.6f}", f"{mid_rec_node:.6f}", f"{tail_rec_node:.6f}", f"{mixed_rec_node:.6f}",
                    int(base_rec_seq == best_recovery_seq)
                ])
        except Exception as e:
            log(f"[train] Warning: failed to log metrics: {e}")

        # also aggregate for cross-epoch CSV
        aggregated_overall_rows.append([
            epoch, f"{base_rec_node:.6f}", f"{top_rec_node:.6f}", f"{mid_rec_node:.6f}", f"{tail_rec_node:.6f}", f"{mixed_rec_node:.6f}"
        ])

    # Write overall validation recoveries across epochs
    try:
        with open(overall_agg_path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['epoch', 'baseline', 'top', 'mid', 'tail', 'mixed'])
            for row in aggregated_overall_rows:
                writer.writerow(row)
        log(f"Saved overall validation recoveries to: {overall_agg_path}")
    except Exception as e:
        log(f"[train] Warning: failed to write overall validation recoveries: {e}")

    # ----- Test evaluation (mid checkpoint + prior_top, only Seq recovery) -----
    try:
        test_ids = list_graph_ids(args.graph_root, args.test_split)
        test_ds = RNAsolo(test_ids, baseDIR=args.graph_root + '/')
        test_loader = DataLoader(test_ds, batch_size=args.batch_size, shuffle=False)

        # 仅加载 best_mid.pt
        try:
            run_ckpt_variant = os.path.join(run_dir, 'best_mid.pt')
            if os.path.exists(run_ckpt_variant):
                ckpt_v = torch.load(run_ckpt_variant, map_location=device)
            else:
                base_name, ext = os.path.splitext(args.save_name)
                variant_save = os.path.join(args.save_dir, f"{base_name}_mid{ext}")
                ckpt_v = torch.load(variant_save, map_location=device)
            diffusion.load_state_dict(ckpt_v['model'])
        except Exception as e_load:
            log(f"[train] Warning: failed to load best_mid checkpoint: {e_load}")
            raise

        @torch.no_grad()
        def eval_seq_recovery_prior_top(test_loader, test_dataset_size):
            diffusion.eval()
            # 统计 QCBM 样本频次，构建 prior_top 集合
            test_prior_samples = torch.tensor(qcbm.sample(num_samples=2048), dtype=torch.float32, device=device)
            perm = torch.randperm(test_prior_samples.shape[0], device=device)
            test_prior_samples = test_prior_samples[perm]
            bits_np = (test_prior_samples.detach().cpu().numpy()).astype(np.int64)
            uniques, counts = np.unique(bits_np, axis=0, return_counts=True)
            order = np.argsort(counts)[::-1]
            u = order.shape[0]
            top_end = int(0.2 * u)
            top_bits = uniques[order[:top_end]]
            prior_top_set = torch.tensor(top_bits, dtype=torch.float32, device=device) if top_bits.size > 0 else torch.empty((0, test_prior_samples.shape[1]), dtype=torch.float32, device=device)
            # 按测试集大小采样 prior_top（与 gid 对齐）
            def sample_prior_from_set(prior_set, size):
                if prior_set.shape[0] == 0 or size == 0:
                    return torch.empty((0, test_prior_samples.shape[1]), dtype=torch.float32, device=device)
                idx = torch.randint(low=0, high=prior_set.shape[0], size=(size,), device=device)
                return prior_set[idx]
            prior_top = sample_prior_from_set(prior_top_set, test_dataset_size)

            # 计算仅序列级恢复率
            per_seq_rec_list = []
            for batch in test_loader:
                data = batch.to(device)
                gids = torch.unique_consecutive(data.gid)
                if prior_top.shape[0] == 0:
                    continue
                prior_bits_graph = prior_top[gids.tolist()]
                _, pred_logits = diffusion.forward(data, logit=True, prior_bits_per_graph=prior_bits_graph, w=args.prior_weight)
                pred_seq = F.one_hot(pred_logits.argmax(dim=1), num_classes=4).float()
                _, ind = seq_recovery(data, pred_seq)
                if hasattr(data, 'batch'):
                    uniq = torch.unique(data.batch)
                    for gid in uniq:
                        mask = (data.batch == gid)
                        if mask.any():
                            per_seq_rec_list.append(ind[mask].float().mean().item())
            avg_rec_seq = (sum(per_seq_rec_list) / len(per_seq_rec_list)) if len(per_seq_rec_list) > 0 else float('nan')
            return avg_rec_seq, prior_top

        top_rec_seq, saved_prior_top = eval_seq_recovery_prior_top(test_loader, len(test_ids))
        log(f"Test (best_mid.pt + prior_top) Recovery (Seq): {top_rec_seq:.4f}")

        # 保存 prior_top 与 test_ids 以便后续 test_q.py 验证
        try:
            saved_prior_dir = os.path.join(run_dir, 'saved_priors')
            variant_dir = os.path.join(saved_prior_dir, 'best_mid')
            os.makedirs(variant_dir, exist_ok=True)
            prior_path_v = os.path.join(variant_dir, 'prior_top_testset.pt')
            torch.save({'prior_top': saved_prior_top.detach().cpu(), 'test_ids': test_ids}, prior_path_v)
            log(f"[test] Saved best_mid prior_top samples for seq_generator_q: {prior_path_v}")
        except Exception as e_save:
            log(f"[train] Warning: failed to save prior_top samples: {e_save}")

        # 仅保存序列级恢复率到 CSV
        try:
            test_seq_csv = os.path.join(run_dir, 'test_seq_recovery_mid_top.csv')
            with open(test_seq_csv, 'w', newline='') as f:
                writer = csv.writer(f)
                writer.writerow(['top_rec_seq'])
                writer.writerow([f"{top_rec_seq:.6f}"])
            log(f"Saved Seq recovery (best_mid + prior_top): {test_seq_csv}")
        except Exception as e_csv:
            log(f"[train] Warning: failed to write seq recovery CSV: {e_csv}")
    except Exception as e:
        log(f"[train] Warning: test inference skipped: {e}")

if __name__ == '__main__':
    main()
